[package]
name = "sonic-ucse"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>", "Noemi Glaeser <nglaeser@umd.edu>"]
edition = "2018"

[dependencies.pairing]
version = "0.14"
features = ["u128-support"]

[dependencies]
merlin = "2"
rand = "0.7"
bellman = "0.1.0"
lamport_sigs = "0.7.0"
ring = "0.16.15"
ed25519-dalek = "1"
elgamal = { path = "rust-elgamal" }
curv-kzen = "0.9.0"
curve25519-dalek = "3.2.1"
starsig = { path = "starsig" }

[dependencies.sapling-crypto]
git = "https://github.com/zcash-hackworks/sapling-crypto"
rev = "eb409fa3cf8df215ae8d35f5e385751a0c5ffb85"